---
- name: Include dynamic variables
  hosts: all
  tasks:
  - include_tasks: ../dynamic-assignment/env_vars.yml
    tags:
      - always


- hosts: all
- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

- hosts: nginx
- import_playbook: ../static-assignments/nginx.yml