---
# - name: Include dynamic variables
#   hosts: all
#   tasks:
#   - include_tasks: ../dynamic-assignments/env-vars.yml
#     tags:
#       - always

- name: Import common-del.yml playbook
  hosts: all
- import_playbook: ../static-assignments/common-del.yml

# - name: Loadbalancers assignment
#   hosts: lb
# - import_playbook: ../static-assignments/lb.yml
#   when: load_balancer_is_required 
