---
- name: Include dynamic variables
  hosts: all
  tasks:
  - include_tasks: ../dynamic-assignment/env_vars.yml
    tags:
      - always

- name: Import common.yml playbook
  hosts: all
- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- name: webserver
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

- hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml